import { NextResponse } from 'next/server'
import { GoogleGenerativeAI } from '@google/generative-ai'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!)

export async function POST(request: Request) {
  try {
    const { description, uploadedDocs } = await request.json()
    
    const model = genAI.getGenerativeModel({ model: 'gemini-pro' })
    
    const prompt = `
      As a senior full-stack developer, generate a complete Next.js 14 application.
      Requirements: ${description}
      Additional docs: ${uploadedDocs.join(', ')}
      
      Provide the complete code in this exact format:
      FILE: app/page.tsx
      CODE: // Full code here
      FILE: next.config.js
      CODE: // Full code here
      ...etc
    `
    
    const result = await model.generateContent(prompt)
    const response = await result.response.text()
    
    // Parse response into files
    const files = parseAICodeResponse(response)
    
    return NextResponse.json({ files, analysis: 'Generated by Gemini AI' })
  } catch (error) {
    return NextResponse.json(
      { error: 'AI service error' },
      { status: 500 }
    )
  }
}

function parseAICodeResponse(text: string) {
  // Parse FILE: ... CODE: ... format
  const files = []
  const lines = text.split('\n')
  let currentFile = null
  
  for (const line of lines) {
    if (line.startsWith('FILE:')) {
      if (currentFile) files.push(currentFile)
      currentFile = { path: line.replace('FILE:', '').trim(), content: '' }
    } else if (line.startsWith('CODE:') && currentFile) {
      currentFile.content = line.replace('CODE:', '').trim()
    } else if (currentFile && currentFile.content) {
      currentFile.content += '\n' + line
    }
  }
  if (currentFile) files.push(currentFile)
  
  return files
      }
